#ifndef IT_GAMES_UI_HTML_H
#define IT_GAMES_UI_HTML_H

static const char *g_ui_html = 
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"  <title>IT Games - PS5 FreeShop</title>"
"  <style>"
"    :root { --bg: #0b0e14; --card-bg: #141923; --accent: #00d2ff; --accent-glow: rgba(0, 210, 255, 0.4); --text: #f0f4fc; --subtext: #7e8b9b; --focus-border: #00e5ff; }"
"    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; user-select: none; }"
"    body { background: var(--bg); color: var(--text); min-height: 100vh; overflow-x: hidden; padding: 40px; }"
"    header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 20px; margin-bottom: 30px; }"
"    .brand { display: flex; align-items: center; gap: 15px; }"
"    .logo-badge { background: linear-gradient(135deg, #0088ff, #00e5ff); color: #000; font-weight: 900; font-size: 24px; padding: 8px 16px; border-radius: 12px; box-shadow: 0 0 20px var(--accent-glow); }"
"    .brand h1 { font-size: 28px; font-weight: 800; letter-spacing: 1px; }"
"    .hud { display: flex; gap: 20px; font-size: 14px; font-weight: 600; }"
"    .hud-chip { background: var(--card-bg); padding: 8px 16px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.05); display: flex; gap: 8px; align-items: center; }"
"    .hud-val { color: var(--accent); }"
"    .nav-tabs { display: flex; gap: 15px; margin-bottom: 30px; }"
"    .tab { padding: 12px 24px; border-radius: 10px; font-weight: 700; cursor: pointer; background: var(--card-bg); color: var(--subtext); transition: all 0.2s; border: 2px solid transparent; }"
"    .tab.active, .tab:focus { color: #fff; background: #1a2233; border-color: var(--focus-border); box-shadow: 0 0 15px var(--accent-glow); outline: none; }"
"    .game-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 25px; }"
"    .game-card { background: var(--card-bg); border-radius: 16px; overflow: hidden; border: 2px solid transparent; transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1); outline: none; display: flex; flex-direction: column; cursor: pointer; position: relative; }"
"    .game-card:focus, .game-card.selected { transform: translateY(-8px) scale(1.02); border-color: var(--focus-border); box-shadow: 0 12px 30px rgba(0, 210, 255, 0.3); }"
"    .cover-wrap { width: 100%; height: 160px; background: #1f2738; display: flex; align-items: center; justify-content: center; font-size: 48px; border-bottom: 1px solid rgba(255,255,255,0.05); position: relative; }"
"    .badge { position: absolute; top: 12px; right: 12px; background: rgba(0,0,0,0.7); font-size: 11px; font-weight: 800; padding: 4px 8px; border-radius: 6px; text-transform: uppercase; }"
"    .info { padding: 18px; display: flex; flex-direction: column; flex-grow: 1; justify-content: space-between; }"
"    .info h3 { font-size: 18px; margin-bottom: 6px; font-weight: 700; }"
"    .info p { font-size: 13px; color: var(--subtext); margin-bottom: 15px; }"
"    .btn-action { background: linear-gradient(135deg, #0066cc, #00aaff); color: #fff; border: none; padding: 10px; border-radius: 8px; font-weight: 700; cursor: pointer; text-align: center; }"
"    .controller-bar { position: fixed; bottom: 20px; left: 50%; transform: translateX(-50%); background: rgba(15,20,30,0.9); backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.1); padding: 10px 24px; border-radius: 30px; display: flex; gap: 20px; font-size: 13px; font-weight: 600; box-shadow: 0 10px 30px rgba(0,0,0,0.5); z-index: 100; }"
"    .c-hint { display: flex; align-items: center; gap: 6px; }"
"    .c-btn { width: 22px; height: 22px; border-radius: 50%; background: #253047; color: #fff; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 900; }"
"    .toast { position: fixed; top: 30px; right: 30px; background: #00e5ff; color: #000; padding: 14px 24px; border-radius: 12px; font-weight: 800; box-shadow: 0 10px 30px rgba(0,229,255,0.4); display: none; z-index: 1000; animation: slideIn 0.3s; }"
"    @keyframes slideIn { from { transform: translateY(-30px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }"
"  </style>"
"</head>"
"<body>"
"  <div class='toast' id='toast'>Notification Sent!</div>"
"  <header>"
"    <div class='brand'>"
"      <div class='logo-badge'>IT</div>"
"      <div>"
"        <h1>IT GAMES</h1>"
"        <div style='font-size: 12px; color: var(--accent); font-weight: 700;'>NATIVE PS5 FREESHOP & HOMEBREW MANAGER</div>"
"      </div>"
"    </div>"
"    <div class='hud'>"
"      <div class='hud-chip'><span>USER:</span> <span class='hud-val' id='hud-user'>Achie</span></div>"
"      <div class='hud-chip'><span>SOC TEMP:</span> <span class='hud-val' id='hud-soc'>--°C</span></div>"
"      <div class='hud-chip'><span>CPU TEMP:</span> <span class='hud-val' id='hud-cpu'>--°C</span></div>"
"      <div class='hud-chip'><span>STORAGE:</span> <span class='hud-val' id='hud-storage'>821 GB Free</span></div>"
"    </div>"
"  </header>"
"  <div class='nav-tabs'>"
"    <button class='tab active' tabindex='1'>Featured Games</button>"
"    <button class='tab' tabindex='2'>Homebrew Tools</button>"
"    <button class='tab' tabindex='3'>Installed Library</button>"
"    <button class='tab' tabindex='4' onclick='sendTestNotification()'>Send TV Toast</button>"
"  </div>"
"  <div class='game-grid' id='catalog'>"
"    <div class='game-card' tabindex='5'>"
"      <div class='cover-wrap'>🎮<span class='badge'>v1.0.0</span></div>"
"      <div class='info'>"
"        <div><h3>ShadowMount+</h3><p>Automated PFS & ffpfs background mounter</p></div>"
"        <button class='btn-action' onclick='installGame(\"ShadowMount+\")'>Installed</button>"
"      </div>"
"    </div>"
"    <div class='game-card' tabindex='6'>"
"      <div class='cover-wrap'>⚡<span class='badge'>v2.6B</span></div>"
"      <div class='info'>"
"        <div><h3>etaHEN All-in-One</h3><p>Core system daemon, Toolbox & kstuff</p></div>"
"        <button class='btn-action' onclick='installGame(\"etaHEN\")'>Active</button>"
"      </div>"
"    </div>"
"    <div class='game-card' tabindex='7'>"
"      <div class='cover-wrap'>🌐<span class='badge'>v1.2.0</span></div>"
"      <div class='info'>"
"        <div><h3>Garlic Save Manager</h3><p>Decrypted PS5 save exporter with web interface</p></div>"
"        <button class='btn-action' onclick='installGame(\"Garlic\")'>Download (2.1 MB)</button>"
"      </div>"
"    </div>"
"    <div class='game-card' tabindex='8'>"
"      <div class='cover-wrap'>🕹️<span class='badge'>v0.17</span></div>"
"      <div class='info'>"
"        <div><h3>CheatRunner</h3><p>Real-time game memory trainer & cheat engine</p></div>"
"        <button class='btn-action' onclick='installGame(\"CheatRunner\")'>Download (3.4 MB)</button>"
"      </div>"
"    </div>"
"  </div>"
"  <div class='controller-bar'>"
"    <div class='c-hint'><div class='c-btn'>✕</div> Select / Download</div>"
"    <div class='c-hint'><div class='c-btn'>◯</div> Back</div>"
"    <div class='c-hint'><div class='c-btn'>△</div> Refresh</div>"
"    <div class='c-hint'><div class='c-btn'>◻</div> System Info</div>"
"  </div>"
"  <script>"
"    function showToast(msg) {"
"      const t = document.getElementById('toast');"
"      t.innerText = msg;"
"      t.style.display = 'block';"
"      setTimeout(() => t.style.display = 'none', 3000);"
"    }"
"    function sendTestNotification() {"
"      fetch('/api/notify?msg=🎮 IT Games 4K Native Engine Online!')"
"        .then(r => r.json())"
"        .then(d => showToast('Toast Sent to TV!'));"
"    }"
"    function installGame(name) {"
"      showToast('Downloading & Installing ' + name + '...');"
"      fetch('/api/download?name=' + encodeURIComponent(name))"
"        .then(r => r.json())"
"        .then(d => showToast(name + ' Ready!'));"
"    }"
"    function pollTelemetry() {"
"      fetch('/api/sysinfo')"
"        .then(r => r.json())"
"        .then(d => {"
"          if(d.gamertag) document.getElementById('hud-user').innerText = d.gamertag;"
"          if(d.soc_temp) document.getElementById('hud-soc').innerText = d.soc_temp + '°C';"
"          if(d.cpu_temp) document.getElementById('hud-cpu').innerText = d.cpu_temp + '°C';"
"        }).catch(() => {});"
"    }"
"    setInterval(pollTelemetry, 2000);"
"    pollTelemetry();"
"    // DualSense Controller Gamepad Support"
"    let lastPad = 0;"
"    function pollGamepad() {"
"      const pads = navigator.getGamepads ? navigator.getGamepads() : [];"
"      if(pads && pads[0]) {"
"        const gp = pads[0];"
"        const now = Date.now();"
"        if(now - lastPad > 200) {"
"          if(gp.buttons[12] && gp.buttons[12].pressed) moveFocus(-1);"
"          if(gp.buttons[13] && gp.buttons[13].pressed) moveFocus(1);"
"          if(gp.buttons[0] && gp.buttons[0].pressed) { if(document.activeElement) document.activeElement.click(); }"
"          if(gp.buttons[3] && gp.buttons[3].pressed) sendTestNotification();"
"          lastPad = now;"
"        }"
"      }"
"      requestAnimationFrame(pollGamepad);"
"    }"
"    function moveFocus(dir) {"
"      const focusable = Array.from(document.querySelectorAll('.tab, .game-card'));"
"      let idx = focusable.indexOf(document.activeElement);"
"      if(idx === -1) idx = 0;"
"      else idx = (idx + dir + focusable.length) % focusable.length;"
"      focusable[idx].focus();"
"    }"
"    requestAnimationFrame(pollGamepad);"
"    window.onload = () => {"
"      const first = document.querySelector('.game-card');"
"      if(first) first.focus();"
"    };"
"  </script>"
"</body>"
"</html>";

#endif // IT_GAMES_UI_HTML_H
